// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using learnVocabularyApi.Data;

namespace learnVocabularyApi.Migrations
{
    [DbContext(typeof(LearnEnglishContext))]
    [Migration("20190811085148_addTotalWords")]
    partial class addTotalWords
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("learnVocabularyApi.Models.Vocab", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Example");

                    b.Property<bool>("IsLearning");

                    b.Property<bool>("IsMarked");

                    b.Property<string>("Name");

                    b.Property<string>("Pronunciation");

                    b.Property<string>("Type");

                    b.HasKey("id");

                    b.ToTable("Vocab");
                });

            modelBuilder.Entity("learnVocabularyApi.Models.Writing", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Topic");

                    b.Property<int>("TotalWords");

                    b.HasKey("id");

                    b.ToTable("Writing");
                });
#pragma warning restore 612, 618
        }
    }
}
