export const GET_WRITINGS = "GET_WRITINGS";
export const ADD_WRITING = "ADD_WRITING";
export const GET_WRITINGS_DONE = "GET_WRITINGS_DONE";
export const ADD_WRITING_DONE = "ADD_WRITING_DONE";
export const DELETE_WRITING = "DELETE_WRITING";
export const DELETE_WRITING_DONE = "DELETE_WRITING_DONE";
export const EDIT_WRITING = "EDIT_WRITING";
export const EDIT_WRITING_DONE = "EDIT_WRITING_DONE";
export const GET_WRITING_BY_ID = "GET_WRITING_BY_ID";
export const GET_WRITING_BY_ID_DONE = "GET_WRITING_BY_ID_DONE";

